set(_CATKIN_CURRENT_PACKAGE "robosys")
set(robosys_VERSION "0.0.0")
set(robosys_MAINTAINER "carl <carl.moser@students.olin.edu>")
set(robosys_PACKAGE_FORMAT "2")
set(robosys_BUILD_DEPENDS "roscpp" "rospy" "std_msgs" "sensor_msgs" "image_transport" "cv_bridge")
set(robosys_BUILD_EXPORT_DEPENDS )
set(robosys_BUILDTOOL_DEPENDS "catkin")
set(robosys_BUILDTOOL_EXPORT_DEPENDS )
set(robosys_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "sensor_msgs" "image_transport" "cv_bridge")
set(robosys_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "sensor_msgs" "image_transport" "cv_bridge")
set(robosys_TEST_DEPENDS )
set(robosys_DOC_DEPENDS )
set(robosys_URL_WEBSITE "")
set(robosys_URL_BUGTRACKER "")
set(robosys_URL_REPOSITORY "")
set(robosys_DEPRECATED "")